# Class Examples

General Libraries to use:

In [1]:
import torch
import numpy as np
import seaborn

In [2]:
# Histogram example using torch
m_x = torch.tensor([0.0,1,1,0,0,1,0,0,0,1])

hist, bin_edges = torch.histogram(m_x,bins=torch.tensor([0.0,0.5,1]))

print("hist \n", hist)
print("bin_edges \n", bin_edges)

hist 
 tensor([6., 4.])
bin_edges 
 tensor([0.0000, 0.5000, 1.0000])


In [3]:
# Normalizando
N = m_x.shape[0]

p_x = hist/N

print(f"{p_x}\n")
print(f"Sum of values of p_x: {torch.sum(p_x)}\n")

tensor([0.6000, 0.4000])

Sum of values of p_x: 1.0



In [4]:
# Create gaussian data sample
n = 10000
normal_dist = torch.distributions.Normal(torch.tensor([10.0]), torch.tensor([2]))
gaussian_sample = normal_dist.sample((n,1)).squeeze() # Change a 2D tensor to a 1D tensor

print(f"Gaussian Sample:\n {gaussian_sample}")

Gaussian Sample:
 tensor([12.5379,  9.4725, 11.5335,  ..., 10.0038,  8.5075, 10.7348])


In [6]:
# Creating histogram
histogram_gaussian, bin_gaussian = np.histogram(gaussian_sample.numpy(),bins = 20,range = (0,20))

# Normalizing
p_gaussian = torch.tensor(histogram_gaussian/histogram_gaussian.sum())

# Plot created with Mathplotlib
# plot_bar(bin_gaussian[1:0], histogram_gaussian, "x", "p(x)", "Histogram with fixed bin size, Gaussian Sample")