## Practica Bayes

In [1]:
import torch
import numpy as np

### Funciones Generales

In [2]:
def get_marginal_probabilities_classes(M_data):
    # Creando las categorias
    categoria1 = M_data[0]
    categoria2 = M_data[1]

    N = torch.sum(M_data)

    sum_c1 = torch.sum(categoria1)
    sum_c2 = torch.sum(categoria2)

    p_t = torch.tensor([[sum_c1/N],[sum_c2/N]])

    return p_t

In [3]:
def get_conditional_probability_p_m_given_t(M_data):
    # Separando por t
    t0_array = M_data[0,:]
    t1_array = M_data[1,:]

    m_t0 = torch.tensor([[t0_array[0],t0_array[2]],[t0_array[1],t0_array[3]]])
    m_t1 = torch.tensor([[t1_array[0],t1_array[2]],[t1_array[1],t1_array[3]]])

    m_t0_sum_0 = torch.sum(m_t0[:,0])
    m_t0_sum_1 = torch.sum(m_t0[:,1])
    print(m_t0_sum_1)
    p_m_t0 = torch.concat([m_t0[:,0]/m_t0_sum_0,m_t0[:,1]/m_t0_sum_1])
    p_m_t0 = p_m_t0.view(2,2)

    m_t1_sum_0 = torch.sum(m_t1[:,0])
    m_t1_sum_1 = torch.sum(m_t1[:,1])
    p_m_t1 = torch.concat([m_t1[:,0]/m_t1_sum_0,m_t1[:,1]/m_t1_sum_1])
    p_m_t1 = p_m_t1.view(2,2)

    return p_m_t0,p_m_t1

### Definicion de matriz

In [4]:
M_data = torch.tensor([[20.0,70,80,10],[40,10,30,5]])
print(M_data)

tensor([[20., 70., 80., 10.],
        [40., 10., 30.,  5.]])


In [14]:
p_t = get_marginal_probabilities_classes(M_data)
print(p_t)

tensor([[0.6792],
        [0.3208]])


In [6]:
p_m_t0,p_m_t1 = get_conditional_probability_p_m_given_t(M_data)

tensor(90.)


In [7]:
print("Probabilidad condicionada de t=0:\n",p_m_t0)

Probabilidad condicionada de t=0:
 tensor([[0.2222, 0.7778],
        [0.8889, 0.1111]])


In [8]:
print("Probabilidad condicionada de t=1:\n",p_m_t1)

Probabilidad condicionada de t=1:
 tensor([[0.8000, 0.2000],
        [0.8571, 0.1429]])


### Creando el hypercubo

In [13]:
K = 2
D = 2
Z = 2

density_cube = torch.zeros(K,D,Z)

# t=0
density_cube[0,:,:] = p_m_t0

# t=1
density_cube[1,:,:] = p_m_t1

print(density_cube)

tensor([[[0.2222, 0.7778],
         [0.8889, 0.1111]],

        [[0.8000, 0.2000],
         [0.8571, 0.1429]]])


In [57]:
def estimate_label(x, density_cube, p_t):
    score = density_cube[0,0,x[0]] * density_cube[0,1,x[1]] * p_t[0]
    return  score

In [58]:
# Inferencia para t=0
m_1 = torch.tensor([0,0])
m_2 = torch.tensor([1,0])
m_3 = torch.tensor([1,1])

In [59]:
# Calculando los scores para t=0
label1_score = estimate_label(m_1,density_cube,p_t)
print(f"Score para m_1 = {label1_score}")

Score para m_1 = tensor([0.1342])


In [60]:
label2_score = estimate_label(m_2,density_cube,p_t)
print(f"Score para m_2 = {label2_score}")

Score para m_2 = tensor([0.4696])


In [61]:
label3_score = estimate_label(m_3,density_cube,p_t)
print(f"Score para m_3 = {label3_score}")

Score para m_3 = tensor([0.0587])
